apiVersion: apps/v1
kind: Deployment
metadata:
  name: disclosure-checker-production
  namespace: disclosure-checker-production
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: disclosure-checker-web-production
  template:
    metadata:
      labels:
        app: disclosure-checker-web-production
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/family-justice/disclosure-checker:production.latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 125m
            memory: 500Mi
          limits:
            cpu: 250m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /ping.json
            port: 3000
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Ssl
                value: "on"
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping.json
            port: 3000
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Ssl
                value: "on"
          initialDelaySeconds: 30
          periodSeconds: 10
        # non-secret env vars defined in `config_map.yaml`
        envFrom:
          - configMapRef:
              name: disclosure-checker-configmap-production
        env:
          # external secrets defined in `secrets.yml`
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: disclosure-checker-secrets-production
                key: secret_key_base
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: disclosure-checker-secrets-production
                key: sentry_dsn
          #
          # secrets created by `terraform`
          #
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-disclosure-checker-production
                key: url
