AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

####################################
## Customization for this project ##
####################################

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 132

Metrics/MethodLength:
  Max: 19

Metrics/AbcSize:
  Max: 19
