# Note: in production we are forcing SSL and certificate verification.
# The RDS certificates bundle is downloaded in the Dockerfile.
#
# Refer to https://www.postgresql.org/docs/current/libpq-ssl.html for more information.
#
default: &default
  adapter: postgresql

development:
  database: disclosure_checker_development
  <<: *default
test:
  database: disclosure_checker_test
  <<: *default
production:
  database: disclosure_checker_production
  <<: *default
