name: ECR images cleaner
author: zheileman
description: Cleanup images from ECR based on pushed date, keeping images in use in replica sets history.
inputs:
  ecr-repo-name:
    required: true
    description: Name of the ECR repository, usually is team-name/app-name
  additional-tags-regex:
    required: true
    description: Additional image tags that should not be deleted (regex)
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/ecr-cleanup.sh
      shell: bash
      env:
        ECR_REPO_NAME: ${{ inputs.ecr-repo-name }}
        ADDITIONAL_TAGS_REGEX: ${{ inputs.additional-tags-regex }}
