{
 "title": "Family Justice / Disclosure Checker",
 "tags": [ "family justice" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Replicas",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace='$namespace'}) by (deployment)"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{namespace='$namespace'}) by (deployment)"
    }
   ]
  },
  {
   "title": "Cron Job Schedule",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_cronjob_status_last_schedule_time{namespace='$namespace'}) by (cronjob) * 1000"
    },
    {
     "expr": "min(kube_cronjob_next_schedule_time{namespace='$namespace'}) by (cronjob) * 1000"
    }
   ]
  },
  {
   "title": "Cron Job History",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_job_status_start_time{namespace='$namespace'}) by (job_name) * 1000"
    },
    {
     "expr": "max(kube_job_status_completion_time{namespace='$namespace'}) by (job_name) * 1000"
    },
    {
     "expr": "sum(kube_job_status_succeeded{namespace='$namespace'}) by (job_name)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{namespace='$namespace'})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace',container='webapp'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace',container='webapp'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{namespace='$namespace'}[5m]))",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='$namespace',container='webapp'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='$namespace',container='webapp'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}